### ISSUE TITLE
Vulkan bindings

### ISSUE THREAD

**Issue by amerkoleci** [FaberSanZ/Zeckoxe-Engine#1]
Hi,

I saw your issue on my repository, just wanted to let you know that I'm bindings latest vulkan 1.2.x bindings.

You can track the progress here: https://github.com/amerkoleci/Vortice.Vulkan

Cheers,
Amer

**Comment by FaberSanZ** [comment]
Hi @amerkoleci, 

Great, I look forward to a stable version, I'll be on the lookout.
